<a href="https://colab.research.google.com/github/MellowFluff/Explicit-Lyrics-classifier/blob/main/label_data.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
!pip install transformers -q

     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 7.5/7.5 MB 61.2 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 268.8/268.8 kB 28.7 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 7.8/7.8 MB 98.4 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.3/1.3 MB 67.0 MB/s eta 0:00:00


In [ ]:
from transformers import AutoModelForSequenceClassification
from transformers import AutoTokenizer

import numpy as np
import pandas as pd
import torch
from tqdm.auto import tqdm

In [ ]:
#download tokenizer and model
MODEL = "cardiffnlp/twitter-roberta-base-offensive"

tokenizer = AutoTokenizer.from_pretrained(MODEL)
model = AutoModelForSequenceClassification.from_pretrained(MODEL)

In [ ]:
#infer a few sentences
text = ["Hands up!"]

def label_with_big_model(text):
    encoded_input = tokenizer(text, return_tensors='pt', padding=True)
    output = model(**encoded_input)
    scores = torch.softmax(output[0],1).detach().numpy()
    return scores #return as array([non-explicit score, explicit score]); non-explicit score + explicit score = 1.

label_with_big_model(text)

array([[0.8793057 , 0.12069436]], dtype=float32)

In [ ]:
task='offensive'
MODEL = f"cardiffnlp/twitter-roberta-base-{task}"

tokenizer = AutoTokenizer.from_pretrained(MODEL)

In [ ]:
df2 = pd.read_csv('/content/lyriconlytest.csv')
#df2 = df.head(100)
df2

In [ ]:
score_list = []
total_rows = df2.shape[0]
batch_size = 100

for i in tqdm(range(total_rows//batch_size)):
    scores = label_with_big_model(df2.iloc[i*batch_size:(i+1)*batch_size,0].tolist())[:,1]
    score_list+=list(scores)

  0%|          | 0/1296 [00:00<?, ?it/s]

In [ ]:
score_list

In [ ]:
df2['explicit_score'] = pd.Series(score_list)

<ipython-input-75-de5d2c3c503c>:1: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df2['explicit_score'] = pd.Series(score_list)


In [ ]:
df2

lyrics  explicit_score
0                    They see me mowin' my front lawn        0.219210
1   I know they're all thinking I'm so white and n...        0.682778
2                      I wanna roll with the gangstas        0.521088
3   But so far they all think I'm too white and nerdy        0.512022
4                      Really, really white and nerdy        0.518113
..                                                ...             ...
95     Never to the movies, just straight to my house        0.316671
96        You said it yourself, you like it like I do        0.091571
97  Put your lips on my dick, and suck my asshole too        0.858600
98         I'm a freak in heat, a dog without warning        0.749273
99              My appetite is sex, cause me so horny        0.681959

[100 rows x 2 columns]

In [ ]:
df.to_csv('labeledlyric.csv')

# New Section

In [ ]:
df = pd.read_csv('/content/musicclean beforelable.csv')
df2 = df.head(100)
df2

In [ ]:
df = pd.read_csv('/content/musicclean beforelable.csv')

#df['lyrics']


    #print(df['lyrics'][ind])


text1 = df['lyrics'][0]
label_with_big_model(text1)


#for x in df.lyrics.tolist():
  #text = df.lyrics.tolist()[x]
  #print(text)
  #label_with_big_model(text)

array([[0.78078955, 0.21921045]], dtype=float32)

In [ ]:
text = df['lyrics'][1]
label_with_big_model(text)

array([[0.3172218 , 0.68277824]], dtype=float32)

In [ ]:
score_list = []
text = df['lyrics'][0]
#df['df.index']

for i in tqdm(range(129000)):
  for ind in df.index:
      scores = label_with_big_model(text)[:,1]
      score_list+=list(scores)
      ind += 1

df['explicit'] = pd.Series(score_list)

#for x in df.lyrics.tolist():
  #text = df.lyrics.tolist()[x]
  #print(text)
  #label_with_big_model(text)

  0%|          | 0/129000 [00:00<?, ?it/s]

KeyboardInterrupt: ignored

In [ ]:
score_list = []
batch_size = 500
#df['df.index']

for ind in df.index:
    #print(df['lyrics'][ind])
    text = df['lyrics'][ind]
    #scores = label_with_big_model(text)[:,1]
    scores = label_with_big_model(text[i*batch_size:(i+1)*batch_size,0].tolist())[:,1]
    score_list+=list(scores)

TypeError: ignored

In [ ]:
df.lyrics.tolist()

In [ ]:
score_list = []
total_rows = df2.shape[0]
batch_size = 50

for i in tqdm(range(total_rows//batch_size)):
    scores = label_with_big_model(df2.iloc[i*batch_size:(i+1)*batch_size,0].tolist())[:,1]
    score_list+=list(scores)

In [ ]:
score_list

In [ ]:
df2['explicit_score'] = pd.Series(score_list)

<ipython-input-55-de5d2c3c503c>:1: FutureWarning: The default dtype for empty Series will be 'object' instead of 'float64' in a future version. Specify a dtype explicitly to silence this warning.
  df2['explicit_score'] = pd.Series(score_list)


In [ ]:
df2

0                                  They see me mowin' my front lawn
1                 I know they're all thinking I'm so white and n...
2                                    I wanna roll with the gangstas
3                 But so far they all think I'm too white and nerdy
4                                    Really, really white and nerdy
                                        ...                        
96                      You said it yourself, you like it like I do
97                Put your lips on my dick, and suck my asshole too
98                       I'm a freak in heat, a dog without warning
99                            My appetite is sex, cause me so horny
explicit_score                           Series([], dtype: float64)
Name: lyrics, Length: 101, dtype: object