<a href="https://colab.research.google.com/github/MellowFluff/Explicit-Lyrics-classifier/blob/main/Machine_learning.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
!pip install -U scikit-learn

In [ ]:
import pandas as pd
import numpy as np
import csv
import matplotlib.pyplot as plt

In [ ]:
df = pd.read_csv('/content/trainingdatacomplete.csv')
df

Unnamed: 0         title               artist  \
0                0  White  Nerdy  "Weird Al" Yankovic   
1                1  White  Nerdy  "Weird Al" Yankovic   
2                2  White  Nerdy  "Weird Al" Yankovic   
3                3  White  Nerdy  "Weird Al" Yankovic   
4                4  White  Nerdy  "Weird Al" Yankovic   
...            ...           ...                  ...   
129656      129656      Hands Up                eLZhi   
129657      129657      Hands Up                eLZhi   
129658      129658      Hands Up                eLZhi   
129659      129659      Hands Up                eLZhi   
129660      129660      Hands Up                eLZhi   

                                                   lyrics  text_order  \
0                        They see me mowin' my front lawn           1   
1       I know they're all thinking I'm so white and n...           2   
2                          I wanna roll with the gangstas           3   
3       But so far they all think I'm too white and nerdy           4   
4                          Really, really white and nerdy           5   
...                                                   ...         ...   
129656  Alright I will! (nice and slow, this ain't you...         116   
129657                                (Put your hands up)         117   
129658                                        Put 'em up!         118   
129659                 Freeze!, freeze!, freeze!, freeze!         119   
129660                                          Hands up!         120   

        explicit_score  explicit_count  explicit  non-explicit  
0             0.219211               0         0             1  
1             0.682778               1         1             0  
2             0.521088               0         0             1  
3             0.512022               0         0             1  
4             0.518114               0         0             1  
...                ...             ...       ...           ...  
129656        0.107254               0         0             1  
129657        0.146758               0         0             1  
129658        0.156626               0         0             1  
129659        0.202729               0         0             1  
129660        0.120694               0         0             1  

[129661 rows x 9 columns]

split

label x and y

fitting

training

In [ ]:
#label x and y

x = df['lyrics']
y = df['explicit_count']

In [ ]:
#split data 20%

from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelEncoder
from sklearn import preprocessing
from sklearn import utils

label_transformed = LabelEncoder()
y_transformed = label_transformed.fit_transform(y)

x_train, x_test, y_train_transformed, y_test_transformed = train_test_split(x, y_transformed, test_size=0.2)

In [ ]:
x_test

In [ ]:
#ใช้ classifier LinerSVC

from sklearn.pipeline import Pipeline
from sklearn.feature_extraction.text import CountVectorizer, TfidfTransformer
from sklearn.svm import LinearSVC

Model = Pipeline([
    ('vect', CountVectorizer()),
    ('tfidf', TfidfTransformer()),
    ('clf', LinearSVC()),
    ])

#train model
Model.fit(x_train, y_train_transformed)

/usr/local/lib/python3.10/dist-packages/sklearn/svm/_classes.py:32: FutureWarning: The default value of `dual` will change from `True` to `'auto'` in 1.5. Set the value of `dual` explicitly to suppress the warning.
  warnings.warn(


Pipeline(steps=[('vect', CountVectorizer()), ('tfidf', TfidfTransformer()),
                ('clf', LinearSVC())])

In [ ]:
#test set

label_mapping = {0: 'non-explicit', 1: 'explicit'}
pred_labels_transformed = Model.predict(x_test)

print(x_test)
print(pred_labels_transformed)

pred_labels = label_transformed.inverse_transform(pred_labels_transformed)

testset_df = pd.DataFrame({'lyrics': x_test, 'predicted_label': pred_labels})
testset_df['explicit_count'] = testset_df['predicted_label'].map(label_mapping)
testset_df.to_csv('predictiontestset.csv', index=False)

pred_df = pd.read_csv('predictiontestset.csv')
pred_df

82255               And she know I get high, a-bove the law
29625     Then my boys just slide out, but two girls wer...
14461                                   Rich Boy, ? fool, ?
126841          Tryin' to get a clutch at what I could not—
118776                              And it's still all good
                                ...                        
91304     The days of the pork fried rice and the chicke...
39309     Me and Dre had sat with him, kicked it and had...
46308           Shorty say what it do is what I make 'er do
64750     Tell her, "Please forgive me," then squeeze in...
13135                       Wind fellows and land merchants
Name: lyrics, Length: 25933, dtype: object
[0 0 1 ... 0 0 0]


lyrics  predicted_label  \
0                And she know I get high, a-bove the law                0   
1      Then my boys just slide out, but two girls wer...                0   
2                                    Rich Boy, ? fool, ?                1   
3            Tryin' to get a clutch at what I could not—                0   
4                                And it's still all good                0   
...                                                  ...              ...   
25928  The days of the pork fried rice and the chicke...                0   
25929  Me and Dre had sat with him, kicked it and had...                0   
25930        Shorty say what it do is what I make 'er do                0   
25931  Tell her, "Please forgive me," then squeeze in...                0   
25932                    Wind fellows and land merchants                0   

      explicit_count  
0       non-explicit  
1       non-explicit  
2           explicit  
3       non-explicit  
4       non-explicit  
...              ...  
25928   non-explicit  
25929   non-explicit  
25930   non-explicit  
25931   non-explicit  
25932   non-explicit  

[25933 rows x 3 columns]

In [ ]:
#check report metrics and accuracy

from sklearn.metrics import classification_report, confusion_matrix, accuracy_score
y_true = y_test_transformed
y_pred = pred_labels

target_names = ['explicit', 'non-explicit']
print(classification_report(y_true, y_pred, target_names=target_names))

confusionmatrix = confusion_matrix(y_true, y_pred)
print(confusionmatrix)

accuracy = accuracy_score(y_true, y_pred)
print(accuracy)

# precision    recall  f1-score   support

    #explicit       0.95      0.98      0.96     20291
#non-explicit       0.91      0.81      0.86      5642

    #accuracy                           0.94     25933
   #macro avg       0.93      0.89      0.91     25933
#weighted avg       0.94      0.94      0.94     25933

#[[19852   439]
 #[ 1098  4544]]
#0.9407318860139591

              precision    recall  f1-score   support

    explicit       0.95      0.98      0.96     20291
non-explicit       0.91      0.81      0.86      5642

    accuracy                           0.94     25933
   macro avg       0.93      0.89      0.91     25933
weighted avg       0.94      0.94      0.94     25933

[[19852   439]
 [ 1098  4544]]
0.9407318860139591


In [ ]:
#ดึงมาใช้

input = ['bitch']

pred = Model.predict(input)
pred_labels = label_transformed.inverse_transform(pred)

predict_df = pd.DataFrame({'lyrics': input, 'predicted_label': pred_labels})
predict_df['explicit_count'] = predict_df['predicted_label'].map(label_mapping)

predict_df

lyrics  predicted_label explicit_count
0  bitch                1       explicit

In [ ]:
def pred_lyrics(input):
    input = [input]
    pred = Model.predict(input)
    label_ex = [label_mapping[label] for label in pred]
    return label_ex

In [ ]:
pred_lyrics('bitch')

['explicit']

In [ ]:
import joblib

In [ ]:
# save model with joblib
filename = 'explicit_lyrics_classifier.sav'
joblib.dump(Model, filename)

['explicit_lyrics_classifier.sav']